### ISSUE TITLE
D.R.Y Styles with HTML classes

### ISSUE THREAD

**Issue by zannain** [dundundawn/prj-rev-bwfs-dasmoto#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is one of the most well know programming principles. If you find yourself repeating certain styles as you do with (here)[https://github.com/dundundawn/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css) this is an indication that you may want to simplify your stylesheet by making use of classes. 

By creating a class with style(s) that repeat over again you don't have to repeat those styles but rather just give an element that class which is much more efficient than repeating styles. It's also more flexible because if you ever wanted to change styles you only have to change the styles one for that class and all elements with that class will receive those style(s). 

```css
#frames{
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: lightcoral;
}
#paint{
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: skyblue;
}
```
Instead you can refactor to &darr; 
```css
.basics {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
}
```

```html
<div class = "basics">...</div>
<div class= "basics">...</div>
```
